grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: 5
      max_depth: 6
      learning_rate: 0.05
      subsample: 0.8
      colsample_bytree: 0.7
      objective: 'binary:logistic'
    search_param_grid:
      min_samples_leaf:
      - 6