columns:
  age: int
  workclass: object
  fnlwgt: float
  education: object
  education-num: float
  marital-status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital-gain: float
  capital-loss: float
  hours-per-week: float
  country: object

numerical_columns:
  - age
  - capital-gain
  - capital-loss
  - education-num
  - fnlwgt
  - hours-per-week

categorical_columns:
 - education
 - marital-status
 - country
 - occupation
 - race
 - relationship
 - sex
 - workclass

target_column: salary